import type { TokidProfileManifest } from "../types.js";
import { OPENAI_CROSS_V1_PROFILE } from "./openai-cross-v1.generated.js";
import { OPENAI_CROSS_UNDERSCORE_V1_PROFILE } from "./openai-cross-underscore-v1.generated.js";

// Generated by tools/profile-compiler.mjs. Do not edit by hand.
export const DEFAULT_PROFILE_ID = "openai-cross-v1";
export {
  OPENAI_CROSS_V1_PROFILE,
  OPENAI_CROSS_UNDERSCORE_V1_PROFILE,
};
export const embeddedProfiles: readonly TokidProfileManifest[] = Object.freeze([
  OPENAI_CROSS_V1_PROFILE,
  OPENAI_CROSS_UNDERSCORE_V1_PROFILE,
]);
